"""Chapter 1 schematic drawings (our own, generated by code) used by the notebook to keep cells short.

    from scripts.ch01_drawings import draw_wedge, draw_cube_forces, draw_capillary, draw_triangle_split, draw_parcel_column

Each helper draws on a given matplotlib Axes and returns it. They draw geometry only; any numbers shown come from the
tested ``fluidpy`` functions.

Run: ``.venv/Scripts/python.exe scripts/ch01_drawings.py --no-show`` (gallery → outputs/ch01/fig_drawings.png).
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fluidpy.core.style import COLORS  # noqa: E402


def _arrow(ax, x, y, dx, dy, color, lw=2.0, label=None, **kw):
    ax.annotate("", xy=(x + dx, y + dy), xytext=(x, y), arrowprops=dict(arrowstyle="-|>", color=color, lw=lw))
    if label:
        ax.text(x + dx, y + dy, label, color=color, fontsize=10, **kw)


def draw_wedge(ax, dz: float = 1.0, theta: float = np.radians(35.0)):
    """Triangular fluid element of Fig. 1.5 (§1.7): sloping face ds at angle θ, bottom dx, vertical face dz.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
    dz : float
        Vertical face length (drawing units).
    theta : float
        Slope angle [rad].

    Returns
    -------
    ax
    """
    dx = dz / np.tan(theta)
    P = np.array([[0.0, 0.0], [dx, 0.0], [dx, dz], [0.0, 0.0]])
    ax.fill(P[:, 0], P[:, 1], color=COLORS["blue"], alpha=0.12)
    ax.plot(P[:, 0], P[:, 1], color=COLORS["ink"], lw=1.5)
    s = 0.35 * max(dx, dz)
    mid = np.array([dx / 2, dz / 2])
    n = np.array([-np.sin(theta), np.cos(theta)])  # outward normal of the sloping face
    _arrow(ax, *(mid + n * s), *(-n * s), COLORS["orange"])
    ax.text(*(mid + n * 1.1 * s), r"$p_1\,ds$", color=COLORS["orange"], ha="right", va="bottom", fontsize=10)
    _arrow(ax, dx / 2, -s, 0, 0.9 * s, COLORS["orange"])
    ax.text(dx / 2 + 0.05 * s, -s, r"$p_2\,dx$", color=COLORS["orange"], ha="left", va="bottom", fontsize=10)
    _arrow(ax, dx + s, dz / 2, -0.9 * s, 0, COLORS["orange"])
    ax.text(dx + s, dz / 2 + 0.05 * s, r"$p_3\,dz$", color=COLORS["orange"], ha="right", va="bottom", fontsize=10)
    ax.text(0.18 * dx, 0.04 * dz, r"$\theta$", fontsize=11)
    ax.set_aspect("equal")
    ax.set_xlim(-0.6 * s, dx + 1.6 * s)
    ax.set_ylim(-1.4 * s, dz + 1.2 * s)
    ax.axis("off")
    return ax


def draw_cube_forces(ax):
    """Fluid cube of Fig. 1.6 (§1.7) in oblique projection with the bottom (p) and top (p + dp) pressure forces.

    Returns
    -------
    ax
    """
    o = np.array([0.45, 0.3])  # oblique offset for depth
    front = np.array([[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]], dtype=float)
    back = front + o
    ax.plot(front[:, 0], front[:, 1], color=COLORS["ink"])
    ax.plot(back[:, 0], back[:, 1], color=COLORS["ink"], ls="--", lw=0.8)
    for i in range(4):
        ax.plot([front[i, 0], back[i, 0]], [front[i, 1], back[i, 1]], color=COLORS["ink"], lw=0.8)
    c = np.array([0.5, 0.5]) + o / 2
    _arrow(ax, c[0], 1.9, 0, -0.55, COLORS["orange"])
    ax.text(c[0] + 0.08, 1.75, r"$(p+dp)\,dx\,dy$", color=COLORS["orange"], ha="left", va="center", fontsize=10)
    _arrow(ax, c[0], -0.9, 0, 0.55, COLORS["orange"])
    ax.text(c[0] + 0.08, -0.75, r"$p\,dx\,dy$", color=COLORS["orange"], ha="left", va="center", fontsize=10)
    _arrow(ax, c[0], c[1] + 0.15, 0, -0.35, COLORS["rose"])
    ax.text(c[0] + 0.08, c[1] - 0.05, r"$\rho g\,dx\,dy\,dz$", color=COLORS["rose"], ha="left", va="center",
            fontsize=10)
    ax.text(0.5, -0.12, "dx", ha="center", va="top")
    ax.text(1.05, 0.5, "dz", va="center")
    ax.set_aspect("equal")
    ax.set_xlim(-0.8, 2.2)
    ax.set_ylim(-1.1, 2.1)
    ax.axis("off")
    return ax


def draw_capillary(ax, R: float = 1.0, alpha: float = np.radians(70.0), h: float = 3.0):
    """Liquid rising a height h in a tube of radius R (Example 1.1, Fig. 1.7), meniscus meeting the wall at the book's α.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
    R : float
        Tube radius (drawing units).
    alpha : float
        The book's angle between meniscus tangent and horizontal at the wall [rad] (π/2 = full wetting).
    h : float
        Rise of the meniscus bottom above the outside level (drawing units).

    Returns
    -------
    ax
    """
    wall = 0.15 * R
    ax.fill_between([-4 * R, 4 * R], -1.5 * R, 0, color=COLORS["blue"], alpha=0.12)
    for sgn in (-1, 1):
        ax.fill_between([sgn * R, sgn * (R + wall)], -1.0 * R, h + 1.5 * R, color=COLORS["muted"], alpha=0.5)
    # spherical meniscus of radius R/sin(alpha), concave up, bottom at height h
    Rm = R / max(np.sin(alpha), 1e-3)
    x = np.linspace(-R, R, 100)
    y = h + Rm - np.sqrt(np.maximum(Rm ** 2 - x ** 2, 0.0))
    ax.fill_between(x, -1.5 * R, y, color=COLORS["blue"], alpha=0.25)
    ax.plot(x, y, color=COLORS["blue"], lw=2)
    ax.plot([-4 * R, -R - wall], [0, 0], color=COLORS["blue"], lw=2)
    ax.plot([R + wall, 4 * R], [0, 0], color=COLORS["blue"], lw=2)
    yw = y[-1]
    _arrow(ax, R, yw, 0.9 * R * np.cos(alpha), 0.9 * R * np.sin(alpha), COLORS["rose"], label=r"$\sigma$")
    ax.annotate("", xy=(-3 * R, h), xytext=(-3 * R, 0), arrowprops=dict(arrowstyle="<->", color=COLORS["ink"]))
    ax.text(-3.1 * R, h / 2, "h", ha="right", va="center")
    ax.plot([-3.2 * R, -R], [h, h], color=COLORS["muted"], lw=0.8, ls=":")
    ax.text(0, -0.2 * R, "F", ha="center", va="top")
    ax.text(0, h - 0.15 * R, "E", ha="center", va="top")
    ax.set_aspect("equal")
    ax.set_xlim(-4 * R, 4 * R)
    ax.set_ylim(-1.5 * R, h + 1.8 * R)
    ax.axis("off")
    return ax


def draw_triangle_split(ax, beta: float = np.radians(30.0)):
    """Right triangle of Example 1.3 (Fig. 1.10) split by the altitude to the hypotenuse into two similar triangles.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
    beta : float
        Smallest acute angle [rad].

    Returns
    -------
    ax
    """
    C = 1.0
    B, A = C * np.cos(beta), C * np.sin(beta)  # legs adjacent to and opposite β
    P0, P1, P2 = np.array([0.0, 0.0]), np.array([B, 0.0]), np.array([0.0, A])  # right angle at P0, β at P1
    foot = P1 + (P2 - P1) * np.dot(P0 - P1, P2 - P1) / np.dot(P2 - P1, P2 - P1)
    ax.fill(*np.array([P0, foot, P1]).T, color=COLORS["teal"], alpha=0.25)
    ax.fill(*np.array([P0, P2, foot]).T, color=COLORS["orange"], alpha=0.25)
    ax.plot(*np.array([P0, P1, P2, P0]).T, color=COLORS["ink"])
    ax.plot(*np.array([P0, foot]).T, color=COLORS["ink"], ls="--")
    ax.text(B / 2, -0.04, "B", ha="center", va="top")
    ax.text(-0.03, A / 2, "A", ha="right", va="center")
    ax.text(*(0.5 * (P1 + P2) + [0.03, 0.03]), "C")
    ax.text(B - 0.17, 0.02, r"$\beta$")
    ax.set_aspect("equal")
    ax.axis("off")
    return ax


def draw_parcel_column(ax, z=None, T_env=None, z0: float = 500.0, zeta: float = 300.0):
    """Environment temperature profile with a parcel lifted from z0 by ζ along its dry adiabat (Fig. 1.8/1.9 idea).

    Parameters
    ----------
    ax : matplotlib.axes.Axes
    z : array_like, optional
        Heights [m] (default 0–2000 m).
    T_env : array_like, optional
        Environment temperature at ``z`` [K] (default: standard troposphere, dT/dz = −6.5 K/km).
    z0 : float
        Rest height of the parcel [m].
    zeta : float
        Displacement [m].

    Returns
    -------
    ax
    """
    from fluidpy.ch01_introduction import parcel_temperature

    z = np.linspace(0.0, 2000.0, 201) if z is None else np.asarray(z, dtype=float)
    T_env = 288.15 - 6.5e-3 * z if T_env is None else np.asarray(T_env, dtype=float)
    T0 = float(np.interp(z0, z, T_env))
    ax.plot(T_env - 273.15, z, color=COLORS["ink"], lw=2, label="environment T(z)")
    Ta = parcel_temperature(T0, z, z0)  # dry adiabat through the release point (z0, T0)
    ax.plot(Ta - 273.15, z, color=COLORS["teal"], ls="--", label="parcel dry adiabat")
    zp = z0 + zeta
    Tp = float(parcel_temperature(T0, zp, z0))
    Te = float(np.interp(zp, z, T_env))
    ax.scatter([Tp - 273.15], [zp], s=120, color=COLORS["teal"], zorder=3)
    ax.scatter([T0 - 273.15], [z0], s=60, facecolor="white", edgecolor=COLORS["teal"], zorder=3)
    ax.annotate("colder than surroundings → sinks back" if Tp < Te else "warmer than surroundings → keeps rising",
                xy=(Tp - 273.15, zp), xytext=(10, 10), textcoords="offset points", fontsize=9,
                color=COLORS["teal"] if Tp < Te else COLORS["rose"])
    ax.set_xlabel("temperature [°C]")
    ax.set_ylabel("height z [m]")
    ax.legend(loc="lower left")
    return ax


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out", default=str(ROOT / "outputs" / "ch01"), help="figure folder")
    ap.add_argument("--no-show", action="store_true", help="do not open a window")
    args = ap.parse_args()
    t0 = time.perf_counter()
    import matplotlib

    if args.no_show:
        matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    from fluidpy.core.style import use_style

    use_style()
    fig, axs = plt.subplots(1, 5, figsize=(17, 3.8))
    draw_wedge(axs[0])
    draw_cube_forces(axs[1])
    draw_capillary(axs[2])
    draw_triangle_split(axs[3])
    draw_parcel_column(axs[4])
    for ax, t in zip(axs, ["wedge (Fig. 1.5 idea)", "cube (Fig. 1.6 idea)", "capillary (Ex. 1.1)",
                           "similar triangles (Ex. 1.3)", "displaced parcel (§1.10)"]):
        ax.set_title(t)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    fig.savefig(out / "fig_drawings.png", bbox_inches="tight")
    print(f"saved {out / 'fig_drawings.png'}  ({time.perf_counter() - t0:.1f} s)")
    if not args.no_show:
        plt.show()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
